name: Håndball
favicon: null
layout_spectrum: 0.13844562997110188
typography_spectrum: 0.3690159348770976
title: HÅNDBALLBLOGG
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.16752349585294724
  lightness: 0.3246085934806615
  saturation: 0.5880492723081261
  rhythmicContrast: 0.5084238986019045
purpose: []
