name: Håndball
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39683
title: HÅNDBALL-BLOGG
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050213'
    - '#d3ecff'
    - '#4351bf'
    - '#8b9dff'
    - '#ffb897'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5084238986019045
purpose: []
