name: Håndball
favicon: null
layout_spectrum: 0.25323
typography_spectrum: 0.39683
title: HÅNDBALL-BLOGG
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#daa880'
    - '#2bf8fe'
    - '#bd3037'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
