name: Håndball
favicon: null
layout_spectrum: 0.25323
typography_spectrum: 0.39683
title: HÅNDBALL-BLOGG
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c5c8db'
    - '#fefefe'
    - '#72748d'
    - '#514b61'
    - '#260000'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
